apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-w6hy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-w6hy@sha256:0f3a0bb88045937230dc4daae80c4e67d5dfb1a6a513ef5c498e227542e1b193
        name: my-nodejs
        resources: {}
status: {}
